// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCkjz2QoP14cIfYCGPxtJACABxmNkZazA',
    appId: '1:175157490639:web:735dc5f4f3b311f539d8ba',
    messagingSenderId: '175157490639',
    projectId: 'travelapp-b6f0c',
    authDomain: 'travelapp-b6f0c.firebaseapp.com',
    storageBucket: 'travelapp-b6f0c.firebasestorage.app',
    measurementId: 'G-6LCJ6CM885',
    databaseURL: 'https://travelapp-b6f0c-default-rtdb.firebaseio.com/', // <-- Add this
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWEejBx9sAgZKp05Qb0ciBN-HeFAocppc',
    appId: '1:175157490639:android:743bac4dd4dc8b7e39d8ba',
    messagingSenderId: '175157490639',
    projectId: 'travelapp-b6f0c',
    storageBucket: 'travelapp-b6f0c.firebasestorage.app',
    databaseURL: 'https://travelapp-b6f0c-default-rtdb.firebaseio.com/', // <-- Add this
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_12eTLBdavq5ip8WzpVLJKnM8HT5ruxU',
    appId: '1:175157490639:ios:061d9361983fa67f39d8ba',
    messagingSenderId: '175157490639',
    projectId: 'travelapp-b6f0c',
    storageBucket: 'travelapp-b6f0c.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
    databaseURL: 'https://travelapp-b6f0c-default-rtdb.firebaseio.com/', // <-- Add this
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_12eTLBdavq5ip8WzpVLJKnM8HT5ruxU',
    appId: '1:175157490639:ios:061d9361983fa67f39d8ba',
    messagingSenderId: '175157490639',
    projectId: 'travelapp-b6f0c',
    storageBucket: 'travelapp-b6f0c.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
    databaseURL: 'https://travelapp-b6f0c-default-rtdb.firebaseio.com/', // <-- Add this
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCkjz2QoP14cIfYCGPxtJACABxmNkZazA',
    appId: '1:175157490639:web:af76e74a9d0604f439d8ba',
    messagingSenderId: '175157490639',
    projectId: 'travelapp-b6f0c',
    authDomain: 'travelapp-b6f0c.firebaseapp.com',
    storageBucket: 'travelapp-b6f0c.firebasestorage.app',
    measurementId: 'G-781RD0JBK7',
    databaseURL: 'https://travelapp-b6f0c-default-rtdb.firebaseio.com/', // <-- Add this
  );
}